version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: erp_postgres
    environment:
      POSTGRES_DB: erp_system_new
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init:/docker-entrypoint-initdb.d
    networks:
      - erp_network

  # FastAPI Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp_api
    environment:
      - DATABASE_URL=postgresql+psycopg2://erp_user:erp_password@postgres:5432/erp_system_new
      - CORS_ORIGINS=http://localhost:3000
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=oISYtW09OnjvyhwwZWhT
      - MINIO_SECRET_KEY=r48gI52eceNdKenMyu25h5OQA3TTdPDtjhIRAGw1
      - MINIO_BUCKET=erp-reports
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - erp_network

  # Next.js Frontend
  frontend:
    build:
      context: ./ui/react-app
      dockerfile: Dockerfile
    container_name: erp_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./ui/react-app:/app
      - /app/node_modules
    networks:
      - erp_network

  # MinIO Object Storage for Templates
  minio:
    image: minio/minio:latest
    container_name: erp_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - erp_network

  # Metabase for Dashboards
  metabase:
    image: metabase/metabase:latest
    container_name: erp_metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=erp_user
      - MB_DB_PASS=erp_password
      - MB_DB_HOST=postgres
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data
    networks:
      - erp_network

  # Redis for caching, rate limiting, etc.
  redis:
    image: redis:7-alpine
    container_name: erp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp_network

volumes:
  postgres_data:
  metabase_data:
  minio_data:
  redis_data:

networks:
  erp_network:
    driver: bridge
