"""create new product category

Revision ID: 86bf2f73c082
Revises: 0001
Create Date: 2025-09-07 08:33:26.958224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86bf2f73c082'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(length=1000), nullable=True),
    sa.Column('Category', sa.String(length=100), nullable=True),
    sa.Column('Brand', sa.String(length=50), nullable=True),
    sa.Column('Unit', sa.String(length=50), nullable=True),
    sa.Column('Price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('CostPrice', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=False),
    sa.Column('MinimumStock', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=False),
    sa.Column('UpdatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Code'),
    schema='masterdata'
    )
    op.drop_table('Products')
    op.drop_table('__EFMigrationsHistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name=op.f('PK___EFMigrationsHistory'))
    )
    op.create_table('Products',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('Description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('Category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Price', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('CostPrice', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('StockQuantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('MinimumStock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('IsActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('ImageUrl', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('UpdatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('CreatedBy', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('UpdatedBy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('Products_pkey')),
    sa.UniqueConstraint('Code', name=op.f('Products_Code_key'))
    )
    op.drop_table('Products', schema='masterdata')
    # ### end Alembic commands ###